install.packages("XML")
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("devtools", "tximport", "ShortRead", "GenomicAlignments", "DESeq2")
devtools::install_github("pachterlab/sleuth")
