install.packages("XML")
source("https://bioconductor.org/biocLite.R")
biocLite("devtools")
biocLite("ShortRead", "GenomicAlignments")
biocLite("DESeq2")
biocLite("tximport")
biocLite("rhdf5")
devtools::install_github("pachterlab/sleuth")
